### ISSUE TITLE
License

### ISSUE THREAD

**Issue by jprjr** [LinusU/rust-alac-encoder#5]
Hi there - I saw that this is licensed as Apache-2.0 or MIT in the Cargo.toml file. I wanted to see about adding a `LICENSE` or `COPYING` file to the Repo, or maybe a blurb in the `README`? Something to make Github label this project with the license, makes discovery a bit easier. Thank you!

**Comment by LinusU** [comment]
Sure thing!

https://github.com/LinusU/rust-alac-encoder/commit/5b4538d6958ba882e273439a5ad46f4f6c208990
